version: '3'
services:
  db:
    image: mariadb:10.4.13
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: rememberdb
      MYSQL_USER: hello
      MYSQL_PASSWORD: hello
